---
resources:
  - name: code
    type: git
    source:
      uri: https://github.com/pivotal-gabriel-dumitrescu/node-js-sample.git
      branch: master

  - name: ci-repo
    type: git
    source:
      uri: https://github.com/pivotal-gabriel-dumitrescu/qce.git
      branch: master

jobs:
  - name: node-app
    plan:
    - get: code
      trigger: true
    - get: ci-repo
    - task: install
      file: ci-repo/tasks/install.yml
