---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: codeclimate/codeclimate

inputs:
  - name: ci-repo
  - name: code
  - name: codeclimate-cli
  - name: codeclimate-duplication
  - name: codeclimate-eslint
  - name: codeclimate-fixme
  - name: codeclimate-nodesecurity
  - name: codeclimate-requiresafe

run:
  path:  /bin/sh
  args:
    - -c
    - ci-repo/scripts/codeclimate/install.sh
