---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
  - name: ci-repo
  - name: codeclimate-repo
  - name: codeclimate-duplication
  - name: codeclimate-fixme
  - name: codeclimate-nodesecurity
  - name: codeclimate-requiresafe

run:
  path: ./ci-repo/scripts/codeclimate/install.sh
