---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 4.4.3

inputs:
  - name: ci-repo
  - name: code
run:
  path:  /bin/sh
  args:
    - -c
    - ci-repo/scripts/app/install.sh
